# base
title: nekolr's blog
subtitle: 爱吃咖喱棒的打字员DA☆ZE~
description: 爱吃咖喱棒的打字员DA☆ZE~
url: https://blog.nekolr.com
author: nekolr
language: en
keywords: "nekolr, blog"

# theme
theme: next

# hexo deploy
deploy:
  type: git
  repo: git@github.com:nekolr/nekolr.github.io.git
  branch: master
  message: auto deploy
  name: nekolr
  email: excalibll@163.com

# local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000